[geometry][index]: boost::swap() for unsigned ints changed to std::swap() because of error C2872: 'swap' : ambiguous symbol in msvc 8 and 9.
[SVN r84821]